### ISSUE TITLE
ReadMe says both does return new collection and does not

### ISSUE THREAD

**Issue by selner** [Novactive/NovaCollection#14]
Was taking a look at this project to see if i wanted to use it and noticed a small inconsistency in the readme.

These two items appear to contradict themselves about whether or not they return a new Collection:
* random()	Shuffle and return a new Collection.	❎
* unique()	Deduplicate the collection and return a new Collection.  	❎

The text description says they do return a new Collection but the icon states that they do not.  

Clearly not a critical issue but thought you'd want to know.

**Comment by Plopix** [comment]
Hello @selner,

Well thank you! We will fix that ASAP! cc @nozavroni 

++
