### ISSUE TITLE
Install Travis and other services

### ISSUE THREAD

**Issue by nozavroni** [Novactive/NovaCollection#2]
Install Travis, Scrutinizer, Coveralls, CodeInsight, etc. so that when we create a pull request, there are some obvious indicators of that particular branch/changeset's quality and worthiness of being merged.

- [x] Travis
- [ ] Coveralls
- [ ] StyleCI?
- [ ] CodeInsight?
- [x] Scrutinizer
- [x] Sension Insight?

**Comment by Plopix** [comment]
I think we don't need other. We have code coverage on Scrutinizer
