### ISSUE TITLE
Unit test Collection methods that exist so far.

### ISSUE THREAD

**Issue by nozavroni** [Novactive/NovaCollection#5]
Unit test the methods that have been written so far. 

- [ ] Collection\Collection
    - [x] **toArray**
    - [x] **first**
    - [x] **last**
    - [x] **key**
    - [x] **next**
    - [x] **current**
    - [x] **count**
    - [x] **valid**
    - [x] **rewind**
    - [x] **add**
    - [x] **set**
    - [x] **remove**
    - [x] **get**
    - [x] **containsKey** - This method, in my experience, is typically called "has"
    - [x] **offsetUnset**
    - [x] **offsetExists**
    - [x] **offsetSet**
    - [x] **offsetGet**
    - [x] **each**
    - [ ] **map**
    - [ ] **transform**
    - [ ] **filter**
    - [ ] **prune**
    - [ ] **reduce**
    - [ ] **assert**
    - [x] **combine** *See below for notes about this one
    - [ ] **combineKey**
    - [ ] **flip**
    - [ ] **keys**
    - [ ] **values**
- [ ] Collection\Factory
    - [ ] **create**
    - [ ] **getArrayForItems** - This cannot be tested directly because it's protected. Honestly, I kind of like the idea of either making this method public, or just adding a function called Novactive\to_array. I prefer the function, but I realize that functions in the OO world are almost universally shunned (justified or not), and so I understand if you're reluctant to use too many functions. 

### combine
I originally thought this method was supposed to accept an array|traversable and replace its own values with the new array|traversable's values. This is not the case. If you look at array_combine(), it accepts an array as its first argument and it uses that array's values as the return array's keys and the second argument's values as the return array's values. For example:
```php
$arr = array_combine([
    'key1' => 'keewon',
    'key2' => 'kitu',
    'key3' => 'keethry'
],[
    'KEYONE' => 'one',
    'KEYTWO' => 'two',
    'KEYTHREE' => 'three'
]);
// I thought the above would make $arr equal to this...
[
    'key1' => 'one',
    'key2' => 'two',
    'key3' => 'three'  
]
// but it actually returns this... 
[
    'keewon' => 'one',
    'kitu' => 'two',
    'keethry' => 'three'
]; 
```
The way @plopix wrote the Collection::method() is correct. So good job, @plopix :) _However_, I think it would be useful to have a method that does what I originally thought combine() did. So, I propose we create this method and call it "assign" (for the in-place version). I don't feel like it really _needs_ a version that returns a new collection, but if it does, I'll have to think of another name for that method.

**Comment by Plopix** [comment]
All unit tests are done I think see https://github.com/Novactive/NovaCollection/pull/11
